package bot.tools.locator;

public enum LocatorState {
    LOCATION_WAITING,
    WAITING_FOR_QUERY,
    SETTINGS,
    WAITING_FOR_ADDITIONAL_QUERY_FIRST,
    WAITING_FOR_ADDITIONAL_QUERY_SECOND,
    WAITING_FOR_ADDITIONAL_FUNCTIONAL_NUMBER,
    WAITING_FOR_PLACE_NUMBER
}
